# Generated by Django 5.1 on 2024-08-26 02:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0003_cart'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Cart',
        ),
    ]
