# Generated by Django 5.1 on 2024-08-27 03:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0006_contact'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Contact',
        ),
    ]
