# Generated by Django 5.1 on 2024-08-29 12:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0010_checkout'),
    ]

    operations = [
        migrations.AlterField(
            model_name='checkout',
            name='payment',
            field=models.CharField(choices=[('CC', 'Credit Card'), ('PP', 'PayPal'), ('COD', 'Cash on delivery')], max_length=100),
        ),
        migrations.AlterField(
            model_name='checkout',
            name='phone',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='checkout',
            name='zipcode',
            field=models.IntegerField(null=True),
        ),
    ]
