# Generated by Django 5.1 on 2024-08-29 13:56

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0011_alter_checkout_payment_alter_checkout_phone_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='checkout',
            name='date',
            field=models.DateField(default=datetime.date.today),
        ),
    ]
